const std = @import("std");

const execution = @import("../../execution.zig");
const instructions_ = @import("instructions.zig");
const types = @import("../../types.zig");

const Agent = execution.Agent;
const Executable = @import("Executable.zig");
const Instruction = instructions_.Instruction;
const Reference = types.Reference;
const Value = types.Value;

const Self = @This();

agent: *Agent,
ip: usize,
stack: std.ArrayList(Value),
result: ?Value,
evaluate_call_context: struct {
    reference: ?Reference = null,
},

pub fn init(agent: *Agent) !Self {
    var stack = try std.ArrayList(Value).initCapacity(agent.gc_allocator, 32);
    return .{
        .agent = agent,
        .ip = 0,
        .stack = stack,
        .result = null,
        .evaluate_call_context = .{},
    };
}

pub fn deinit(self: Self) void {
    self.stack.deinit();
}

fn fetchInstruction(self: *Self, executable: Executable) ?Instruction {
    const instructions = executable.instructions.items;
    if (self.ip >= instructions.len) return null;
    defer self.ip += 1;
    return instructions[self.ip];
}

fn fetchConstant(self: *Self, executable: Executable) Value {
    const constants = executable.constants.items;
    const index = self.fetchIndex(executable);
    return constants[index];
}

fn fetchIdentifier(self: *Self, executable: Executable) []const u8 {
    const identifiers = executable.identifiers.items;
    const index = self.fetchIndex(executable);
    return identifiers[index];
}

fn fetchIndex(self: *Self, executable: Executable) Executable.IndexType {
    const b1 = @enumToInt(self.fetchInstruction(executable).?);
    const b2 = @enumToInt(self.fetchInstruction(executable).?);
    return std.mem.bytesToValue(Executable.IndexType, &[_]u8{ b1, b2 });
}

/// 13.3.6.2 EvaluateCall ( func, ref, arguments, tailPosition )
/// https://tc39.es/ecma262/#sec-evaluatecall
fn evaluateCallGetThisValue(maybe_reference: ?Reference) Value {
    // 1. If ref is a Reference Record, then
    if (maybe_reference) |reference| {
        // a. If IsPropertyReference(ref) is true, then
        if (reference.isPropertyReference()) {
            // i. Let thisValue be GetThisValue(ref).
            return reference.getThisValue();
        }
        // b. Else,
        else {
            // i. Let refEnv be ref.[[Base]].
            // ii. Assert: refEnv is an Environment Record.
            const reference_environment = reference.base.environment;

            // iii. Let thisValue be refEnv.WithBaseObject().
            return if (reference_environment.withBaseObject()) |object|
                Value.from(object)
            else
                .undefined;
        }
    }
    // 2. Else,
    else {
        // a. Let thisValue be undefined.
        return .undefined;
    }
}

/// 13.3.6.2 EvaluateCall ( func, ref, arguments, tailPosition )
/// https://tc39.es/ecma262/#sec-evaluatecall
fn evaluateCall(
    agent: *Agent,
    function: Value,
    this_value: Value,
    arguments_list: []const Value,
) !Value {
    // 1-2.
    // NOTE: These are done in the function above, which is called by the prepare_call instruction.

    // 3. Let argList be ? ArgumentListEvaluation of arguments.
    // NOTE: This is part of the generated bytecode.

    // 4. If func is not an Object, throw a TypeError exception.
    if (function != .object) {
        return agent.throwException(
            .type_error,
            try std.fmt.allocPrint(agent.gc_allocator, "{} is not an Object", .{function}),
        );
    }

    // 5. If IsCallable(func) is false, throw a TypeError exception.
    if (!function.isCallable()) {
        return agent.throwException(
            .type_error,
            try std.fmt.allocPrint(agent.gc_allocator, "{} is not callable", .{function}),
        );
    }

    // TODO: 6. If tailPosition is true, perform PrepareForTailCall().

    // 7. Return ? Call(func, thisValue, argList).
    return function.callAssumeCallable(this_value, arguments_list);
}

pub fn run(self: *Self, executable: Executable) !?Value {
    while (self.fetchInstruction(executable)) |instruction| switch (instruction) {
        .evaluate_call => {
            const argument_count = self.fetchIndex(executable);
            var arguments = try std.ArrayList(Value).initCapacity(
                self.agent.gc_allocator,
                argument_count,
            );
            for (0..argument_count) |_| {
                const argument = self.stack.pop();
                try arguments.append(argument);
            }
            std.mem.reverse(Value, arguments.items);
            const this_value = self.stack.pop();
            const function = self.stack.pop();
            self.result = try evaluateCall(
                self.agent,
                function,
                this_value,
                arguments.items,
            );
        },
        .jump => self.ip = self.fetchIndex(executable),
        .jump_conditional => {
            const ip_consequent = self.fetchIndex(executable);
            const ip_alternate = self.fetchIndex(executable);
            const value = self.stack.pop();
            self.ip = if (value.toBoolean()) ip_consequent else ip_alternate;
        },
        .load => try self.stack.append(self.result.?),
        .load_constant => {
            const value = self.fetchConstant(executable);
            try self.stack.append(value);
        },
        .prepare_call => {
            const expression_is_reference = self.fetchIndex(executable) == 1;
            const reference = if (expression_is_reference)
                self.evaluate_call_context.reference.?
            else
                null;
            const this_value = evaluateCallGetThisValue(reference);
            try self.stack.append(this_value);
        },
        .resolve_binding => {
            const name = self.fetchIdentifier(executable);
            const reference = try self.agent.resolveBinding(name, null);
            self.result = try reference.getValue(self.agent);
            self.evaluate_call_context.reference = reference;
        },
        .resolve_this_binding => self.result = try self.agent.resolveThisBinding(),
        .store => self.result = self.stack.pop(),
        .store_constant => {
            const value = self.fetchConstant(executable);
            self.result = value;
        },
        .throw => {
            const value = self.stack.pop();
            self.agent.exception = value;
            // TODO: This will need to change when try/catch are implemented.
            return error.ExceptionThrown;
        },
        _ => unreachable,
    };
    return self.result;
}
