name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
      - uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"
      - uses: https://github.com/Swatinem/rust-cache@v2
      - name: Build kiesel.wasm
        run: |
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe
          # Outputs zig-out/bin/kiesel.wasm, no `mv` needed
      - name: Build kiesel-linux-aarch64
        run: |
          zig build -Dtarget=aarch64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-aarch64
      - name: Build kiesel-linux-riscv64
        run: |
          zig build -Dtarget=riscv64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-riscv64
      - name: Build kiesel-linux-x86
        run: |
          zig build -Dtarget=x86-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86
      - name: Build kiesel-linux-x86_64
        run: |
          zig build -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86_64
      - name: Build kiesel-macos-aarch64
        run: |
          zig build -Dtarget=aarch64-macos-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-aarch64
      - name: Build kiesel-windows-aarch64.exe
        run: |
          # TODO: Enable Intl on Windows once possible
          #       See https://github.com/ziglang/zig/issues/15107#issuecomment-1817993587
          zig build -Dtarget=aarch64-windows-gnu -Doptimize=ReleaseSafe -Denable-intl=false
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-aarch64.exe
      - name: Build kiesel-windows-x86.exe
        run: |
          zig build -Dtarget=x86-windows-gnu -Doptimize=ReleaseSafe -Denable-intl=false
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86.exe
      - name: Build kiesel-windows-x86_64.exe
        run: |
          zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSafe -Denable-intl=false
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86_64.exe
      - name: Build for UEFI
        run: |
          zig build -Dtarget=x86_64-uefi-gnu -Doptimize=ReleaseSafe -Denable-intl=false -Denable-libgc=false -Denable-libregexp=false
          rm -rf zig-out/EFI # Not uploading this one :^)
      - name: Upload binaries and update version.txt
        if: ${{ github.ref_name == 'main' }}
        run: |
          git rev-parse main > zig-out/bin/version.txt
          for file in zig-out/bin/*; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@$file" \
              "https://files.kiesel.dev/upload?path=/files"
          done
