name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.3518+d2be725e4
      - uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"
      - uses: https://github.com/Swatinem/rust-cache@v2
      - name: Create build.sh script
        run: |
          cat > build.sh << EOF
          #!/bin/bash
          # https://github.com/ziglang/zig/issues/15107#issuecomment-1817993587
          if [[ \$1 =~ 'windows' ]]; then
            enable_intl='false'
          else
            enable_intl='true'
          fi
          zig build \
            -Dtarget=\$1 \
            -Doptimize=ReleaseSafe \
            -Denable-intl=\$enable_intl
          # Doesn't apply to Wasm build
          if [ -f zig-out/bin/kiesel ]; then
            mv zig-out/bin/kiesel zig-out/bin/\$2
          fi
          if [ -f zig-out/bin/kiesel.exe ]; then
            mv zig-out/bin/kiesel.exe zig-out/bin/\$2
          fi
          EOF
          chmod +x build.sh
      - name: Create upload.sh script
        run: |
          cat > upload.sh << EOF
          #!/bin/bash
          curl \
            -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
            -F "path=@\$1" \
            "https://files.kiesel.dev/upload?path=/files"
          EOF
          chmod +x upload.sh
      - name: Build and upload kiesel.wasm
        run: |
          ./build.sh wasm32-wasi
          ./upload.sh zig-out/bin/kiesel.wasm
      - name: Build and upload kiesel-linux-aarch64
        run: |
          ./build.sh aarch64-linux-musl kiesel-linux-aarch64
          ./upload.sh zig-out/bin/kiesel-linux-aarch64
      - name: Build and upload kiesel-linux-riscv64
        run: |
          ./build.sh riscv64-linux-musl kiesel-linux-riscv64
          ./upload.sh zig-out/bin/kiesel-linux-riscv64
      - name: Build and upload kiesel-linux-x86
        run: |
          ./build.sh x86-linux-musl kiesel-linux-x86
          ./upload.sh zig-out/bin/kiesel-linux-x86
      - name: Build and upload kiesel-linux-x86_64
        run: |
          ./build.sh x86_64-linux-musl kiesel-linux-x86_64
          ./upload.sh zig-out/bin/kiesel-linux-x86_64
      - name: Build and upload kiesel-macos-aarch64
        run: |
          ./build.sh aarch64-macos-none kiesel-macos-aarch64
          ./upload.sh zig-out/bin/kiesel-macos-aarch64
      - name: Build and upload kiesel-windows-aarch64.exe
        run: |
          ./build.sh aarch64-windows-gnu kiesel-windows-aarch64.exe
          ./upload.sh zig-out/bin/kiesel-windows-aarch64.exe
      - name: Build and upload kiesel-windows-x86.exe
        run: |
          ./build.sh x86-windows-gnu kiesel-windows-x86.exe
          ./upload.sh zig-out/bin/kiesel-windows-x86.exe
      - name: Build and upload kiesel-windows-x86_64.exe
        run: |
          ./build.sh x86_64-windows-gnu kiesel-windows-x86_64.exe
          ./upload.sh zig-out/bin/kiesel-windows-x86_64.exe
      - name: Update version.txt
        run: |
          git rev-parse main > version.txt
          ./upload.sh version.txt
