name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/mlugg/setup-zig@v1
        with:
          version: master
      - uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"
      - uses: https://github.com/Swatinem/rust-cache@v2
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install binutils-mingw-w64
      - name: Build kiesel.wasm
        run: |
          # Building with Intl almost doubles the size, let's try to keep the final blob
          # reasonably small - as a result we build this twice
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe -Denable-intl=false
          # Outputs zig-out/bin/kiesel.wasm, no `mv` needed
      - name: Build kiesel-linux-aarch64
        run: |
          zig build -Dtarget=aarch64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-aarch64
      - name: Build kiesel-linux-arm
        run: |
          zig build -Dtarget=arm-linux-musleabihf -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-arm
      - name: Build kiesel-linux-mips
        run: |
          # Building with Intl spits out several thousand of these, and I'm not sure how to
          # convince Rust or Zig to pick something else:
          # floating point ABI '-msoft-float' is incompatible with target floating point ABI '-mdouble-float'
          zig build -Dtarget=mips-linux-musl -Doptimize=ReleaseSafe -Denable-intl=false
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-mips
      - name: Build kiesel-linux-mips64
        run: |
          zig build -Dtarget=mips64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-mips64
      - name: Build kiesel-linux-powerpc
        run: |
          zig build -Dtarget=powerpc-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-powerpc
      - name: Build kiesel-linux-powerpc64
        run: |
          zig build -Dtarget=powerpc64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-powerpc64
      - name: Build kiesel-linux-riscv64
        run: |
          zig build -Dtarget=riscv64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-riscv64
      - name: Build kiesel-linux-x86
        run: |
          zig build -Dtarget=x86-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86
      - name: Build kiesel-linux-x86_64
        run: |
          zig build -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86_64
      - name: Build kiesel-macos-aarch64
        run: |
          zig build -Dtarget=aarch64-macos-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-aarch64
      - name: Build kiesel-macos-x86_64
        run: |
          zig build -Dtarget=x86_64-macos-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-x86_64
      - name: Build kiesel-windows-aarch64.exe
        run: |
          zig build -Dtarget=aarch64-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-aarch64.exe
      - name: Build kiesel-windows-x86.exe
        run: |
          zig build -Dtarget=x86-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86.exe
      - name: Build kiesel-windows-x86_64.exe
        run: |
          zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86_64.exe
      - name: Build for UEFI
        run: |
          zig build -Dtarget=x86_64-uefi-gnu -Doptimize=ReleaseSafe -Denable-intl=false -Denable-libgc=false -Denable-libregexp=false
          rm -rf zig-out/EFI # Not uploading this one :^)
      - name: Upload binaries and update version.txt
        if: ${{ github.ref_name == 'main' }}
        run: |
          git rev-parse main > zig-out/bin/version.txt
          for file in zig-out/bin/*; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@$file" \
              "https://files.kiesel.dev/upload?path=/files"
          done
