name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # NOTE:
  # - The ReleaseFast builds are being used for benchmarking, ReleaseSafe is noticeably slower
  #   - https://boajs.dev/benchmarks/
  #   - https://ahaoboy.github.io/js-engine-benchmark/
  # - This is split into multiple build jobs to have some level of parallelization. Ideally that
  #   would be fully handled in the Zig build system, which has proven difficult so far.
  #   See: https://codeberg.org/kiesel-js/kiesel/issues/103
  build-linux:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
          cache-size-limit: 5120 # 5 GiB
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Build kiesel-linux-aarch64
        run: |
          # Verify building without NaN-boxing on aarch64.
          zig build -Dtarget=aarch64-linux-musl -Doptimize=ReleaseSafe -Denable-nan-boxing=false
          zig build -Dtarget=aarch64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-aarch64
      - name: Build kiesel-linux-arm
        run: |
          zig build -Dtarget=arm-linux-musleabihf -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-arm
      - name: Build kiesel-linux-mips
        run: |
          zig build -Dtarget=mips-linux-musleabi -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-mips
      - name: Build kiesel-linux-mips64
        run: |
          zig build -Dtarget=mips64-linux-muslabi64 -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-mips64
      - name: Build kiesel-linux-powerpc
        run: |
          zig build -Dtarget=powerpc-linux-musleabihf -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-powerpc
      - name: Build kiesel-linux-powerpc64
        run: |
          zig build -Dtarget=powerpc64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-powerpc64
      - name: Build kiesel-linux-riscv64
        run: |
          zig build -Dtarget=riscv64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-riscv64
      - name: Build kiesel-linux-s390x
        run: |
          zig build -Dtarget=s390x-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-s390x
      - name: Build kiesel-linux-x86
        run: |
          zig build -Dtarget=x86-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86
      - name: Build kiesel-linux-x86_64
        run: |
          # Verify building without NaN-boxing on x86_64.
          zig build -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe -Denable-nan-boxing=false
          zig build -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86_64
      - name: Build kiesel-linux-x86_64 (ReleaseFast)
        run: |
          zig build -Dtarget=x86_64-linux-musl -Doptimize=ReleaseFast
          mv zig-out/bin/kiesel zig-out/bin/kiesel-linux-x86_64-releasefast
      - name: Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: build-linux
          path: zig-out/bin/*

  build-macos:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
          cache-size-limit: 5120 # 5 GiB
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Build kiesel-macos-aarch64
        run: |
          zig build -Dtarget=aarch64-macos-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-aarch64
      - name: Build kiesel-macos-aarch64 (ReleaseFast)
        run: |
          zig build -Dtarget=aarch64-macos-none -Doptimize=ReleaseFast
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-aarch64-releasefast
      - name: Build kiesel-macos-x86_64
        run: |
          zig build -Dtarget=x86_64-macos-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-macos-x86_64
      - name: Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: build-macos
          path: zig-out/bin/*

  build-windows:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
          cache-size-limit: 5120 # 5 GiB
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-mingw-w64
      - name: Build kiesel-windows-aarch64.exe
        run: |
          zig build -Dtarget=aarch64-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-aarch64.exe
      - name: Build kiesel-windows-x86.exe
        run: |
          zig build -Dtarget=x86-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86.exe
      - name: Build kiesel-windows-x86_64.exe
        run: |
          zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86_64.exe
      - name: Build kiesel-windows-x86_64.exe (ReleaseFast)
        run: |
          zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseFast
          mv zig-out/bin/kiesel.exe zig-out/bin/kiesel-windows-x86_64-releasefast.exe
      - name: Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: build-windows
          path: zig-out/bin/*

  build-misc:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
          cache-size-limit: 5120 # 5 GiB
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Build kiesel.wasm
        run: |
          # Building with Intl almost doubles the size, let's try to keep the final blob
          # reasonably small - as a result we build this twice
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe
          zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe -Denable-intl=false -Denable-temporal=false
          # Outputs zig-out/bin/kiesel.wasm, no `mv` needed
      - name: Build kiesel-freebsd-aarch64
        run: |
          zig build -Dtarget=aarch64-freebsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-freebsd-aarch64
      - name: Build kiesel-freebsd-x86
        run: |
          zig build -Dtarget=x86-freebsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-freebsd-x86
      - name: Build kiesel-freebsd-x86_64
        run: |
          zig build -Dtarget=x86_64-freebsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-freebsd-x86_64
      - name: Build kiesel-netbsd-aarch64
        run: |
          zig build -Dtarget=aarch64-netbsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-netbsd-aarch64
      - name: Build kiesel-netbsd-x86
        run: |
          zig build -Dtarget=x86-netbsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-netbsd-x86
      - name: Build kiesel-netbsd-x86_64
        run: |
          zig build -Dtarget=x86_64-netbsd-none -Doptimize=ReleaseSafe
          mv zig-out/bin/kiesel zig-out/bin/kiesel-netbsd-x86_64
      - name: Build kiesel-uefi-x86_64.efi
        run: |
          zig build -Dtarget=x86_64-uefi-gnu -Doptimize=ReleaseSafe -Denable-intl=false -Denable-temporal=false -Denable-libgc=false -Denable-libregexp=false
          mv zig-out/EFI/BOOT/bootx64.efi zig-out/bin/kiesel-uefi-x86_64.efi
      - name: Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: build-misc
          path: zig-out/bin/*

  upload-files:
    if: ${{ forgejo.ref_name == 'main' }}
    needs:
      - build-linux
      - build-macos
      - build-windows
      - build-misc
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Download artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          path: files
          pattern: build-*
          merge-multiple: true
      - name: Upload files
        run: |
          echo "$FORGEJO_SHA" > files/version.txt
          for file in files/*; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@$file" \
              "https://files.kiesel.dev/upload?path=/files"
          done

  docs:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
          cache-size-limit: 4096 # 4 GiB
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mandoc
      - name: Build API docs
        run: |
          zig build docs
      - name: Build manual
        run: |
          mandoc -Thtml docs/kiesel.1 > zig-out/docs/kiesel.1.html
      - name: Upload files
        if: ${{ github.ref_name == 'main' }}
        run: |
          cd zig-out
          find docs -type d | while read -r directory; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "mkdir=${directory}" \
              "https://files.kiesel.dev/upload?path=/"
          done
          find docs -type f | while read -r file; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@${file}" \
              "https://files.kiesel.dev/upload?path=/$(dirname $file)"
          done

  lint:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Check formatting
        run: |
          zig fmt --check .
      - name: Check for unused imports
        run: |
          git clone https://github.com/tusharsadhwani/zigimports
          cd zigimports
          zig build --release=safe
          "./zig-out/bin/zigimports-$(uname -m)-linux" ..

  test:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Run tests
        run: |
          zig build -Denable-intl=false -Denable-temporal=false test
      - name: Build fuzzilli shell
        run: |
          # This doesn't run anything, only make sure it keeps building
          zig build -Denable-intl=false -Denable-temporal=false fuzzilli

  test262:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    env:
      # Re-generate `tools/test262/results.json` when updating this
      TEST262_COMMIT: 18f6ed26276be621ddefee8a2d41dda0ed2aae2f
    steps:
      - name: Check out Kiesel
        uses: https://github.com/actions/checkout@v5
      - name: Check out test262
        run: |
          # NOTE: We can't do this with actions/checkout since it assumes the repo is also on codeberg.org
          git clone https://github.com/tc39/test262
          cd test262
          git checkout $TEST262_COMMIT
      - name: Install Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-10-30 # 1.91
          components: "rust-src"
      - name: Install Node.js
        uses: https://github.com/actions/setup-node@v5
      - name: Install dependencies
        run: |
          # NOTE: jq is already installed in the Docker image
          npm install -g github:CanadaHonk/test262-harness
      - name: Build Kiesel
        run: |
          zig build -Doptimize=ReleaseSafe
      - name: Run test262
        run: |
          ./tools/test262/generate-results.sh ./zig-out/bin/kiesel ./test262 'test/**/*.js' > ./tools/test262/results-new.json
      - name: Compare results
        run: |
          diff -u ./tools/test262/results.json ./tools/test262/results-new.json
