name: Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          cache: false
      - uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"
      - uses: https://github.com/Swatinem/rust-cache@v2
      - run: zig build docs
      - name: Upload files
        run: |
          cd zig-out
          find docs -type d | while read -r directory; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "mkdir=${directory}" \
              "https://files.kiesel.dev/upload?path=/"
          done
          find docs -type f | while read -r file; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@${file}" \
              "https://files.kiesel.dev/upload?path=/$(dirname $file)"
          done
