name: Docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/mlugg/setup-zig@v1
        with:
          version: master
      - uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"
      - uses: https://github.com/Swatinem/rust-cache@v2
      - run: zig build docs
      - name: Compile man-page
        run: sudo apt update && sudo apt install -y mandoc && mandoc -Thtml docs/kiesel.1 > zig-out/docs/kiesel.1.html
      - name: Upload files
        if: ${{ github.ref_name == 'main' }}
        run: |
          cd zig-out
          find docs -type d | while read -r directory; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "mkdir=${directory}" \
              "https://files.kiesel.dev/upload?path=/"
          done
          find docs -type f | while read -r file; do
            curl \
              -u "${{ secrets.ARTIFACT_UPLOAD_USER }}:${{ secrets.ARTIFACT_UPLOAD_PASSWORD }}" \
              -F "path=@${file}" \
              "https://files.kiesel.dev/upload?path=/$(dirname $file)"
          done
