name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      # Pinned to https://github.com/mlugg/setup-zig/pull/7
      - uses: https://github.com/mlugg/setup-zig@2fb886036ef83cf152b35c8278550048c7d09e35
        with:
          version: master
      - run: zig fmt --check .
