name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.3033+031f23117
      - run: zig fmt --check .
