name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
      - run: zig build test
