name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: meow
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          cache: false
      - run: zig build -Denable-intl=false test
