name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.3610+9d27f34d0
      - run: zig build -Denable-intl=false test
