//! 6.1.7.4 Well-Known Intrinsic Objects
//! https://tc39.es/ecma262/#sec-well-known-intrinsic-objects

const std = @import("std");

const builtins = @import("../../builtins.zig");
const execution = @import("../../execution.zig");
const types = @import("../../types.zig");

const Object = types.Object;
const PropertyKey = types.PropertyKey;
const Realm = execution.Realm;

const Intrinsics = @This();

aggregate_error: ?*Object,
aggregate_error_prototype: ?*Object,
array: ?*Object,
array_prototype: ?*Object,
array_prototype_to_string: ?*Object,
array_prototype_values: ?*Object,
array_buffer: ?*Object,
array_buffer_prototype: ?*Object,
array_iterator_prototype: ?*Object,
async_from_sync_iterator_prototype: ?*Object,
async_function: ?*Object,
async_function_prototype: ?*Object,
async_generator_function: ?*Object,
async_generator_function_prototype: ?*Object,
async_generator_prototype: ?*Object,
async_iterator_prototype: ?*Object,
atomics: ?*Object,
big_int: ?*Object,
big_int_prototype: ?*Object,
big_int64_array: ?*Object,
big_int64_array_prototype: ?*Object,
big_uint64_array: ?*Object,
big_uint64_array_prototype: ?*Object,
boolean: ?*Object,
boolean_prototype: ?*Object,
data_view: ?*Object,
data_view_prototype: ?*Object,
date: ?*Object,
date_prototype: ?*Object,
decode_uri: ?*Object,
decode_uri_component: ?*Object,
encode_uri: ?*Object,
encode_uri_component: ?*Object,
@"error": ?*Object,
error_prototype: ?*Object,
escape: ?*Object,
eval: ?*Object,
eval_error: ?*Object,
eval_error_prototype: ?*Object,
finalization_registry: ?*Object,
finalization_registry_prototype: ?*Object,
float16_array: ?*Object,
float16_array_prototype: ?*Object,
float32_array: ?*Object,
float32_array_prototype: ?*Object,
float64_array: ?*Object,
float64_array_prototype: ?*Object,
for_in_iterator_prototype: ?*Object,
function: ?*Object,
function_prototype: ?*Object,
generator_function: ?*Object,
generator_function_prototype: ?*Object,
generator_prototype: ?*Object,
int8_array: ?*Object,
int8_array_prototype: ?*Object,
int16_array: ?*Object,
int16_array_prototype: ?*Object,
int32_array: ?*Object,
int32_array_prototype: ?*Object,
intl: ?*Object,
intl_collator: ?*Object,
intl_collator_prototype: ?*Object,
intl_date_time_format: ?*Object,
intl_date_time_format_prototype: ?*Object,
intl_display_names: ?*Object,
intl_display_names_prototype: ?*Object,
intl_duration_format: ?*Object,
intl_duration_format_prototype: ?*Object,
intl_list_format: ?*Object,
intl_list_format_prototype: ?*Object,
intl_locale: ?*Object,
intl_locale_prototype: ?*Object,
intl_number_format: ?*Object,
intl_number_format_prototype: ?*Object,
intl_plural_rules: ?*Object,
intl_plural_rules_prototype: ?*Object,
intl_relative_time_format: ?*Object,
intl_relative_time_format_prototype: ?*Object,
intl_segmenter: ?*Object,
intl_segmenter_prototype: ?*Object,
intl_segments_prototype: ?*Object,
intl_segment_iterator_prototype: ?*Object,
is_finite: ?*Object,
is_nan: ?*Object,
iterator: ?*Object,
iterator_helper_prototype: ?*Object,
iterator_prototype: ?*Object,
json: ?*Object,
map: ?*Object,
map_prototype: ?*Object,
map_iterator_prototype: ?*Object,
math: ?*Object,
number: ?*Object,
number_prototype: ?*Object,
object: ?*Object,
object_prototype: ?*Object,
object_prototype_to_string: ?*Object,
parse_float: ?*Object,
parse_int: ?*Object,
promise: ?*Object,
promise_prototype: ?*Object,
proxy: ?*Object,
range_error: ?*Object,
range_error_prototype: ?*Object,
reference_error: ?*Object,
reference_error_prototype: ?*Object,
reflect: ?*Object,
reg_exp: ?*Object,
reg_exp_prototype: ?*Object,
reg_exp_string_iterator_prototype: ?*Object,
set: ?*Object,
set_prototype: ?*Object,
set_iterator_prototype: ?*Object,
shared_array_buffer: ?*Object,
shared_array_buffer_prototype: ?*Object,
string: ?*Object,
string_prototype: ?*Object,
string_iterator_prototype: ?*Object,
symbol: ?*Object,
symbol_prototype: ?*Object,
syntax_error: ?*Object,
syntax_error_prototype: ?*Object,
temporal: ?*Object,
temporal_duration: ?*Object,
temporal_duration_prototype: ?*Object,
temporal_instant: ?*Object,
temporal_instant_prototype: ?*Object,
temporal_now: ?*Object,
temporal_plain_date: ?*Object,
temporal_plain_date_prototype: ?*Object,
temporal_plain_date_time: ?*Object,
temporal_plain_date_time_prototype: ?*Object,
temporal_plain_month_day: ?*Object,
temporal_plain_month_day_prototype: ?*Object,
temporal_plain_time: ?*Object,
temporal_plain_time_prototype: ?*Object,
temporal_plain_year_month: ?*Object,
temporal_plain_year_month_prototype: ?*Object,
temporal_zoned_date_time: ?*Object,
temporal_zoned_date_time_prototype: ?*Object,
throw_type_error: ?*Object,
typed_array: ?*Object,
typed_array_prototype: ?*Object,
type_error: ?*Object,
type_error_prototype: ?*Object,
uint8_array: ?*Object,
uint8_array_prototype: ?*Object,
uint8_clamped_array: ?*Object,
uint8_clamped_array_prototype: ?*Object,
uint16_array: ?*Object,
uint16_array_prototype: ?*Object,
uint32_array: ?*Object,
uint32_array_prototype: ?*Object,
unescape: ?*Object,
uri_error: ?*Object,
uri_error_prototype: ?*Object,
weak_map: ?*Object,
weak_map_prototype: ?*Object,
weak_ref: ?*Object,
weak_ref_prototype: ?*Object,
weak_set: ?*Object,
weak_set_prototype: ?*Object,
wrap_for_valid_iterator_prototype: ?*Object,

pub const init: Intrinsics = blk: {
    var intrinsics: Intrinsics = undefined;
    for (std.meta.fieldNames(Intrinsics)) |field_name| {
        @field(intrinsics, field_name) = null;
    }
    break :blk intrinsics;
};

fn Type(comptime field: std.meta.FieldEnum(Intrinsics)) type {
    return switch (field) {
        .aggregate_error => builtins.aggregate_error.constructor,
        .aggregate_error_prototype => builtins.aggregate_error.prototype,
        .array => builtins.array.constructor,
        .array_prototype => builtins.array.prototype,
        .array_buffer => builtins.array_buffer.constructor,
        .array_buffer_prototype => builtins.array_buffer.prototype,
        .array_iterator_prototype => builtins.array_iterator.prototype,
        .async_from_sync_iterator_prototype => builtins.async_from_sync_iterator.prototype,
        .async_function => builtins.async_function.constructor,
        .async_function_prototype => builtins.async_function.prototype,
        .async_generator_function => builtins.async_generator_function.constructor,
        .async_generator_function_prototype => builtins.async_generator_function.prototype,
        .async_generator_prototype => builtins.async_generator.prototype,
        .async_iterator_prototype => builtins.async_iterator.prototype,
        .atomics => builtins.atomics.namespace,
        .big_int => builtins.big_int.constructor,
        .big_int_prototype => builtins.big_int.prototype,
        .big_int64_array => builtins.typed_array.big_int64_array.constructor,
        .big_int64_array_prototype => builtins.typed_array.big_int64_array.prototype,
        .big_uint64_array => builtins.typed_array.big_uint64_array.constructor,
        .big_uint64_array_prototype => builtins.typed_array.big_uint64_array.prototype,
        .boolean => builtins.boolean.constructor,
        .boolean_prototype => builtins.boolean.prototype,
        .data_view => builtins.data_view.constructor,
        .data_view_prototype => builtins.data_view.prototype,
        .date => builtins.date.constructor,
        .date_prototype => builtins.date.prototype,
        .decode_uri => builtins.global.decode_uri_function,
        .decode_uri_component => builtins.global.decode_uri_component_function,
        .encode_uri => builtins.global.encode_uri_function,
        .encode_uri_component => builtins.global.encode_uri_component_function,
        .@"error" => builtins.@"error".constructor,
        .error_prototype => builtins.@"error".prototype,
        .escape => builtins.global.escape_function,
        .eval => builtins.global.eval_function,
        .eval_error => builtins.@"error".eval_error.constructor,
        .eval_error_prototype => builtins.@"error".eval_error.prototype,
        .finalization_registry => builtins.finalization_registry.constructor,
        .finalization_registry_prototype => builtins.finalization_registry.prototype,
        .float16_array => builtins.typed_array.float16_array.constructor,
        .float16_array_prototype => builtins.typed_array.float16_array.prototype,
        .float32_array => builtins.typed_array.float32_array.constructor,
        .float32_array_prototype => builtins.typed_array.float32_array.prototype,
        .float64_array => builtins.typed_array.float64_array.constructor,
        .float64_array_prototype => builtins.typed_array.float64_array.prototype,
        .for_in_iterator_prototype => builtins.for_in_iterator.prototype,
        .function => builtins.function.constructor,
        .function_prototype => builtins.function.prototype,
        .generator_function => builtins.generator_function.constructor,
        .generator_function_prototype => builtins.generator_function.prototype,
        .generator_prototype => builtins.generator.prototype,
        .int8_array => builtins.typed_array.int8_array.constructor,
        .int8_array_prototype => builtins.typed_array.int8_array.prototype,
        .int16_array => builtins.typed_array.int16_array.constructor,
        .int16_array_prototype => builtins.typed_array.int16_array.prototype,
        .int32_array => builtins.typed_array.int32_array.constructor,
        .int32_array_prototype => builtins.typed_array.int32_array.prototype,
        .intl => builtins.intl.namespace,
        .intl_collator => builtins.intl.collator.constructor,
        .intl_collator_prototype => builtins.intl.collator.prototype,
        .intl_date_time_format => builtins.intl.date_time_format.constructor,
        .intl_date_time_format_prototype => builtins.intl.date_time_format.prototype,
        .intl_display_names => builtins.intl.display_names.constructor,
        .intl_display_names_prototype => builtins.intl.display_names.prototype,
        .intl_duration_format => builtins.intl.duration_format.constructor,
        .intl_duration_format_prototype => builtins.intl.duration_format.prototype,
        .intl_list_format => builtins.intl.list_format.constructor,
        .intl_list_format_prototype => builtins.intl.list_format.prototype,
        .intl_locale => builtins.intl.locale.constructor,
        .intl_locale_prototype => builtins.intl.locale.prototype,
        .intl_number_format => builtins.intl.number_format.constructor,
        .intl_number_format_prototype => builtins.intl.number_format.prototype,
        .intl_plural_rules => builtins.intl.plural_rules.constructor,
        .intl_plural_rules_prototype => builtins.intl.plural_rules.prototype,
        .intl_relative_time_format => builtins.intl.relative_time_format.constructor,
        .intl_relative_time_format_prototype => builtins.intl.relative_time_format.prototype,
        .intl_segmenter => builtins.intl.segmenter.constructor,
        .intl_segmenter_prototype => builtins.intl.segmenter.prototype,
        .intl_segments_prototype => builtins.intl.segments.prototype,
        .intl_segment_iterator_prototype => builtins.intl.segment_iterator.prototype,
        .is_finite => builtins.global.is_finite_function,
        .is_nan => builtins.global.is_nan_function,
        .iterator => builtins.iterator.constructor,
        .iterator_helper_prototype => builtins.iterator_helper.prototype,
        .iterator_prototype => builtins.iterator.prototype,
        .json => builtins.json.namespace,
        .map => builtins.map.constructor,
        .map_prototype => builtins.map.prototype,
        .map_iterator_prototype => builtins.map_iterator.prototype,
        .math => builtins.math.namespace,
        .number => builtins.number.constructor,
        .number_prototype => builtins.number.prototype,
        .object => builtins.object.constructor,
        .object_prototype => builtins.object.prototype,
        .parse_float => builtins.global.parse_float_function,
        .parse_int => builtins.global.parse_int_function,
        .promise => builtins.promise.constructor,
        .promise_prototype => builtins.promise.prototype,
        .proxy => builtins.proxy.constructor,
        .range_error => builtins.@"error".range_error.constructor,
        .range_error_prototype => builtins.@"error".range_error.prototype,
        .reference_error => builtins.@"error".reference_error.constructor,
        .reference_error_prototype => builtins.@"error".reference_error.prototype,
        .reflect => builtins.reflect.namespace,
        .reg_exp => builtins.reg_exp.constructor,
        .reg_exp_prototype => builtins.reg_exp.prototype,
        .reg_exp_string_iterator_prototype => builtins.reg_exp_string_iterator.prototype,
        .set => builtins.set.constructor,
        .set_prototype => builtins.set.prototype,
        .set_iterator_prototype => builtins.set_iterator.prototype,
        .shared_array_buffer => builtins.shared_array_buffer.constructor,
        .shared_array_buffer_prototype => builtins.shared_array_buffer.prototype,
        .string => builtins.string.constructor,
        .string_prototype => builtins.string.prototype,
        .string_iterator_prototype => builtins.string_iterator.prototype,
        .symbol => builtins.symbol.constructor,
        .symbol_prototype => builtins.symbol.prototype,
        .syntax_error => builtins.@"error".syntax_error.constructor,
        .syntax_error_prototype => builtins.@"error".syntax_error.prototype,
        .temporal => builtins.temporal.namespace,
        .temporal_duration => builtins.temporal.duration.constructor,
        .temporal_duration_prototype => builtins.temporal.duration.prototype,
        .temporal_instant => builtins.temporal.instant.constructor,
        .temporal_instant_prototype => builtins.temporal.instant.prototype,
        .temporal_now => builtins.temporal.now.namespace,
        .temporal_plain_date => builtins.temporal.plain_date.constructor,
        .temporal_plain_date_prototype => builtins.temporal.plain_date.prototype,
        .temporal_plain_date_time => builtins.temporal.plain_date_time.constructor,
        .temporal_plain_date_time_prototype => builtins.temporal.plain_date_time.prototype,
        .temporal_plain_month_day => builtins.temporal.plain_month_day.constructor,
        .temporal_plain_month_day_prototype => builtins.temporal.plain_month_day.prototype,
        .temporal_plain_time => builtins.temporal.plain_time.constructor,
        .temporal_plain_time_prototype => builtins.temporal.plain_time.prototype,
        .temporal_plain_year_month => builtins.temporal.plain_year_month.constructor,
        .temporal_plain_year_month_prototype => builtins.temporal.plain_year_month.prototype,
        .temporal_zoned_date_time => builtins.temporal.zoned_date_time.constructor,
        .temporal_zoned_date_time_prototype => builtins.temporal.zoned_date_time.prototype,
        .throw_type_error => builtins.throw_type_error.function,
        .typed_array => builtins.typed_array.constructor,
        .typed_array_prototype => builtins.typed_array.prototype,
        .type_error => builtins.@"error".type_error.constructor,
        .type_error_prototype => builtins.@"error".type_error.prototype,
        .uint8_array => builtins.typed_array.uint8_array.constructor,
        .uint8_array_prototype => builtins.typed_array.uint8_array.prototype,
        .uint8_clamped_array => builtins.typed_array.uint8_clamped_array.constructor,
        .uint8_clamped_array_prototype => builtins.typed_array.uint8_clamped_array.prototype,
        .uint16_array => builtins.typed_array.uint16_array.constructor,
        .uint16_array_prototype => builtins.typed_array.uint16_array.prototype,
        .uint32_array => builtins.typed_array.uint32_array.constructor,
        .uint32_array_prototype => builtins.typed_array.uint32_array.prototype,
        .unescape => builtins.global.unescape_function,
        .uri_error => builtins.@"error".uri_error.constructor,
        .uri_error_prototype => builtins.@"error".uri_error.prototype,
        .weak_map => builtins.weak_map.constructor,
        .weak_map_prototype => builtins.weak_map.prototype,
        .weak_ref => builtins.weak_ref.constructor,
        .weak_ref_prototype => builtins.weak_ref.prototype,
        .weak_set => builtins.weak_set.constructor,
        .weak_set_prototype => builtins.weak_set.prototype,
        .wrap_for_valid_iterator_prototype => builtins.wrap_for_valid_iterator.prototype,

        .array_prototype_to_string,
        .array_prototype_values,
        .object_prototype_to_string,
        => unreachable,
    };
}

pub fn getOrCreate(
    intrinsics: *Intrinsics,
    realm: *Realm,
    comptime field: std.meta.FieldEnum(Intrinsics),
) std.mem.Allocator.Error!*Object {
    return @field(intrinsics, @tagName(field)) orelse blk: {
        const intrinsic = switch (field) {
            .array_prototype_to_string => try createProperty(intrinsics, realm, .array_prototype, "toString"),
            .array_prototype_values => try createProperty(intrinsics, realm, .array_prototype, "values"),
            .object_prototype_to_string => try createProperty(intrinsics, realm, .object_prototype, "toString"),
            else => try create(intrinsics, realm, field),
        };
        @field(intrinsics, @tagName(field)) = intrinsic;
        break :blk intrinsic;
    };
}

fn create(
    intrinsics: *Intrinsics,
    realm: *Realm,
    comptime field: std.meta.FieldEnum(Intrinsics),
) std.mem.Allocator.Error!*Object {
    const T = Type(field);
    const agent = realm.agent;
    const object = try T.create(agent, realm);
    object.shape = try object.shape.makeUnique(agent.gc_allocator);
    // Sanity check to ensure there is no dependency loop - creating the object must not
    // (indirectly) rely on itself. If something within `create()` assigned the intrinsic it
    // has been created twice and overwriting it would be a mistake.
    std.debug.assert(@field(intrinsics, @tagName(field)) == null);
    // Once the object has been created, we assign and initialize it. This allows `init()` to have
    // dependency loops, e.g. `Function.prototype` and `Object.prototype`.
    @field(intrinsics, @tagName(field)) = object;
    try T.init(agent, realm, object);
    return object;
}

fn createProperty(
    intrinsics: *Intrinsics,
    realm: *Realm,
    comptime parent_field: std.meta.FieldEnum(Intrinsics),
    comptime key: []const u8,
) std.mem.Allocator.Error!*Object {
    const parent = try intrinsics.getOrCreate(realm, parent_field);
    return parent.getPropertyValueDirect(PropertyKey.from(key)).asObject();
}
