const args = @import("args");
const builtin = @import("builtin");
const std = @import("std");
const kiesel = @import("kiesel");

const gc = @cImport({
    @cInclude("gc.h");
});

const Allocator = std.mem.Allocator;

const Agent = kiesel.execution.Agent;
const ArgumentsList = kiesel.builtins.ArgumentsList;
const Diagnostics = kiesel.language.Diagnostics;
const Object = kiesel.types.Object;
const Realm = kiesel.execution.Realm;
const Script = kiesel.language.Script;
const Value = kiesel.types.Value;
const defineBuiltinFunction = kiesel.utils.defineBuiltinFunction;
const defineBuiltinProperty = kiesel.utils.defineBuiltinProperty;
const ordinaryObjectCreate = kiesel.builtins.ordinaryObjectCreate;

const bdwgc_version_string = std.fmt.comptimePrint("{}.{}.{}", .{
    gc.GC_VERSION_MAJOR,
    gc.GC_VERSION_MINOR,
    gc.GC_VERSION_MICRO,
});

const version = std.fmt.comptimePrint(
    \\kiesel {[kiesel]s}
    \\bdwgc {[bdwgc]s}
    \\zig {[zig]s}
    \\
, .{
    .kiesel = kiesel.version_string,
    .bdwgc = bdwgc_version_string,
    .zig = builtin.zig_version_string,
});

const help =
    \\Usage: kiesel [options] [args]
    \\
    \\Options:
    \\
    \\  -c, --command             Run the given code as a script
    \\  --disable-gc              Disable garbage collection
    \\  --print-ast               Print the parsed AST
    \\  --print-bytecode          Print the generated bytecode
    \\  -p, --print-result        Print the evaluated result
    \\  -v, --version             Print version information and exit
    \\  -h, --help                Print help text and exit
    \\
    \\Arguments:
    \\
    \\  file                      The JS file to run, a REPL is started if omitted
    \\
;

const stdin = std.io.getStdIn().reader();
const stdout = std.io.getStdOut().writer();
const stderr = std.io.getStdErr().writer();

pub const Kiesel = struct {
    pub fn create(realm: *Realm) !Object {
        const kiesel_object = try ordinaryObjectCreate(realm.agent, try realm.intrinsics.@"%Object.prototype%"());
        const gc_object = try ordinaryObjectCreate(realm.agent, try realm.intrinsics.@"%Object.prototype%"());
        try defineBuiltinFunction(gc_object, "collect", collect, 0, realm);
        try defineBuiltinProperty(kiesel_object, "gc", Value.from(gc_object));
        return kiesel_object;
    }

    fn collect(_: *Agent, _: Value, _: ArgumentsList) !Value {
        kiesel.gc.collect();
        return .undefined;
    }
};

fn run(
    allocator: Allocator,
    realm: *Realm,
    file_name: []const u8,
    source_text: []const u8,
) !?Value {
    const agent = realm.agent;

    var diagnostics = Diagnostics.init(allocator);
    defer diagnostics.deinit();

    const script = Script.parse(source_text, realm, null, .{
        .diagnostics = &diagnostics,
        .file_name = file_name,
    }) catch |err| switch (err) {
        error.ParseError => {
            try diagnostics.print(stderr);
            return null;
        },
        error.OutOfMemory => return error.OutOfMemory,
    };

    if (agent.options.debug.print_ast) try script.ecmascript_code.print(stdout);

    return script.evaluate() catch |err| switch (err) {
        error.OutOfMemory => {
            try stderr.writeAll("Out of memory\n");
            return null;
        },
        error.ExceptionThrown => {
            try stderr.print("Uncaught exception: {pretty}\n", .{agent.exception.?});
            return null;
        },
    };
}

fn repl(allocator: Allocator, realm: *Realm) !void {
    while (true) {
        try stdout.print("> ", .{});
        if (try stdin.readUntilDelimiterOrEofAlloc(
            allocator,
            '\n',
            std.math.maxInt(usize),
        )) |source_text| {
            defer allocator.free(source_text);

            // Directly show another prompt when spamming enter, whitespace is evaluated
            // however (and will print 'undefined').
            if (source_text.len == 0) continue;

            if (try run(allocator, realm, "repl", source_text)) |result| {
                try stdout.print("{pretty}\n", .{result});
            }
            // Handled exception & printed something, carry on
            else continue;
        }
        // ^C pressed, exit REPL
        else break;
    }
}

pub fn main() !u8 {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const parsed_args = args.parseForCurrentProcess(struct {
        command: ?[]const u8 = null,
        @"disable-gc": bool = false,
        @"print-ast": bool = false,
        @"print-bytecode": bool = false,
        @"print-result": bool = false,
        version: bool = false,
        help: bool = false,

        pub const shorthands = .{
            .c = "command",
            .p = "print-result",
            .v = "version",
            .h = "help",
        };
    }, allocator, .print) catch return 1;
    defer parsed_args.deinit();

    if (parsed_args.options.version) {
        try stdout.writeAll(version);
        return 0;
    } else if (parsed_args.options.help) {
        try stdout.writeAll(help);
        return 0;
    }

    var agent = try Agent.init(.{
        .debug = .{
            .disable_gc = parsed_args.options.@"disable-gc",
            .print_ast = parsed_args.options.@"print-ast",
            .print_bytecode = parsed_args.options.@"print-bytecode",
        },
    });
    defer agent.deinit();
    try Realm.initializeHostDefinedRealm(&agent, .{});
    const realm = agent.currentRealm();
    try defineBuiltinProperty(realm.global_object, "Kiesel", Value.from(try Kiesel.create(realm)));

    const path = if (parsed_args.positionals.len > 0) parsed_args.positionals[0] else null;
    if (path != null) {
        const file = try std.fs.cwd().openFile(path.?, .{});
        defer file.close();
        const file_name = std.fs.path.basename(path.?);
        const source_text = try file.reader().readAllAlloc(allocator, std.math.maxInt(usize));
        defer allocator.free(source_text);
        if (try run(allocator, realm, file_name, source_text)) |result| {
            try stdout.print("{pretty}\n", .{result});
        } else return 1;
    } else if (parsed_args.options.command) |source_text| {
        if (try run(allocator, realm, "command", source_text)) |result| {
            try stdout.print("{pretty}\n", .{result});
        } else return 1;
    } else {
        try repl(allocator, realm);
    }
    return 0;
}
